# Generated by Django 2.1.7 on 2019-08-07 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SonoffDevices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название устройсва')),
                ('device_id', models.CharField(db_index=True, max_length=12, verbose_name='Идентификатор')),
                ('model', models.CharField(blank=True, max_length=20, null=True, verbose_name='Модель устройства')),
                ('sensor_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип сенсора')),
                ('firmware', models.CharField(blank=True, max_length=10, null=True, verbose_name='Версия прошивки')),
                ('is_online', models.BooleanField(blank=True, default=False, verbose_name='Усройство онлайн')),
                ('signal', models.FloatField(blank=True, default=None, null=True, verbose_name='Качество WIFI сигнала')),
                ('last_temperature', models.FloatField(blank=True, default=None, null=True, verbose_name='Последняя зарегистрированная температура')),
                ('last_humidity', models.FloatField(blank=True, default=None, null=True, verbose_name='Последняя зарегистрированная влажность')),
                ('switch', models.BooleanField(blank=True, default=False, verbose_name='Реле активировано')),
                ('date_of_modify', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('last_on_line', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Время последней активности')),
            ],
        ),
        migrations.CreateModel(
            name='SonoffDevicesValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(blank=True, default=None, null=True, verbose_name='Температура')),
                ('humidity', models.FloatField(blank=True, default=None, null=True, verbose_name='Влажность')),
                ('switch', models.BooleanField(blank=True, default=False, verbose_name='Реле активировано')),
                ('date_of_modify', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('modify_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='devices.SonoffDevices', verbose_name='Устройство')),
            ],
        ),
    ]
