# Generated by Django 2.1.7 on 2019-08-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sonoffdevicesvalues',
            old_name='modify_by',
            new_name='device',
        ),
        migrations.AddField(
            model_name='sonoffdevices',
            name='mac',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='MAC адресс'),
        ),
    ]
