# Generated by Django 2.1.7 on 2019-08-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20190807_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='sonoffdevices',
            name='last_off_line',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Время последнего пропадания из сети'),
        ),
        migrations.AlterField(
            model_name='sonoffdevices',
            name='last_on_line',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Время последнего появления в сети'),
        ),
    ]
