# Generated by Django 2.1.7 on 2019-08-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_auto_20190809_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='sonoffdevices',
            name='humidity_histeresis_value',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Значение гистерезиса по влажности'),
        ),
        migrations.AddField(
            model_name='sonoffdevices',
            name='humidity_maximal_alarm_value',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Верхний порог срабатывания тревоги по влажности'),
        ),
        migrations.AddField(
            model_name='sonoffdevices',
            name='humidity_maximal_warning_value',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Верхний порог срабатывания предуприждения по влажности'),
        ),
        migrations.AddField(
            model_name='sonoffdevices',
            name='humidity_minimal_alarm_value',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Нижний порог срабатывания тревоги по влажности'),
        ),
        migrations.AddField(
            model_name='sonoffdevices',
            name='humidity_minimal_warning_value',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Нижний порог срабатывания предуприждения по влажности'),
        ),
        migrations.AddField(
            model_name='sonoffdevices',
            name='humidity_status',
            field=models.IntegerField(choices=[(0, 'Норма'), (1, 'Предупреждение: значение ниже нормы'), (2, 'Предупреждение: значение выше нормы'), (3, 'Тревога: значение ниже нормы'), (4, 'Тревога: значение выше нормы')], default=0, verbose_name='состояние по влажности'),
        ),
        migrations.AddField(
            model_name='sonoffdevices',
            name='temperature_histeresis_value',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Значение гистерезиса по температуре'),
        ),
        migrations.AddField(
            model_name='sonoffdevices',
            name='temperature_maximal_alarm_value',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Верхний порог срабатывания тревоги по температуре'),
        ),
        migrations.AddField(
            model_name='sonoffdevices',
            name='temperature_maximal_warning_value',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Верхний порог срабатывания предуприждения  по температуре'),
        ),
        migrations.AddField(
            model_name='sonoffdevices',
            name='temperature_minimal_alarm_value',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Нижний порог срабатывания тревоги по температуре'),
        ),
        migrations.AddField(
            model_name='sonoffdevices',
            name='temperature_minimal_warning_value',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Нижний порог срабатывания предуприждения по температуре'),
        ),
        migrations.AddField(
            model_name='sonoffdevices',
            name='temperature_status',
            field=models.IntegerField(choices=[(0, 'Норма'), (1, 'Предупреждение: значение ниже нормы'), (2, 'Предупреждение: значение выше нормы'), (3, 'Тревога: значение ниже нормы'), (4, 'Тревога: значение выше нормы')], default=0, verbose_name='состояние по температуре'),
        ),
    ]
