# Generated by Django 2.2.4 on 2019-08-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20190813_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='sonoffdevicesvalues',
            name='humidity_status',
            field=models.IntegerField(choices=[(0, 'Норма'), (1, 'Предупреждение: значение ниже нормы'), (2, 'Предупреждение: значение выше нормы'), (3, 'Тревога: значение ниже нормы'), (4, 'Тревога: значение выше нормы')], default=0, verbose_name='состояние по влажности'),
        ),
        migrations.AddField(
            model_name='sonoffdevicesvalues',
            name='signal',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Качество WIFI сигнала'),
        ),
        migrations.AddField(
            model_name='sonoffdevicesvalues',
            name='temperature_status',
            field=models.IntegerField(choices=[(0, 'Норма'), (1, 'Предупреждение: значение ниже нормы'), (2, 'Предупреждение: значение выше нормы'), (3, 'Тревога: значение ниже нормы'), (4, 'Тревога: значение выше нормы')], default=0, verbose_name='состояние по температуре'),
        ),
    ]
