# Generated by Django 2.2.4 on 2019-08-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_auto_20190816_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название группы')),
                ('devices', models.ManyToManyField(to='devices.SonoffDevices')),
            ],
        ),
    ]
