# Generated by Django 3.0.2 on 2021-01-18 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_devicegroups'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Имя пользователя')),
                ('humidity_notify', models.BooleanField(blank=True, default=False, verbose_name='Извещать об превышениях по влажности')),
                ('temperature_notify', models.BooleanField(blank=True, default=False, verbose_name='Извещать об превышениях по температуре')),
                ('offline_notify', models.BooleanField(blank=True, default=False, verbose_name='Извещать об пропавших устройствах')),
            ],
            options={
                'verbose_name': 'Пользователи Telegram для оповещений',
            },
        ),
        migrations.AlterModelOptions(
            name='devicegroups',
            options={'verbose_name': 'Группы устройств'},
        ),
        migrations.AlterModelOptions(
            name='sonoffdevices',
            options={'verbose_name': 'Устройства'},
        ),
        migrations.AlterModelOptions(
            name='sonoffdevicesvalues',
            options={'verbose_name': 'Архив значений данных от устройств'},
        ),
        migrations.CreateModel(
            name='DeviceTelegramUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_users', to='devices.SonoffDevices', verbose_name='Устройство')),
                ('telegram_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.TelegramUsers', verbose_name='Пользователь для извещения')),
            ],
            options={
                'verbose_name': 'Telegram для оповещение по устройствам',
            },
        ),
    ]
